### PR TITLE
Feat normtransf optional extrapolation

### PR DESCRIPTION
**Pull request by rhugman**
- Added optional extrapolation for normal score transform in `Eds.prep_for_dsi()`. Can be None, linear or quadratic.
- Added optional ZtZ method from pestutils DSI2

### CODE REVIEW

**Comment by briochh** [comment]
@rhugman, is this one gtg? I know that it breaks with our tradition but do you reckon you could add some lines to the `prep_for_dsi()` docstring on the `ztz` and `energy` options and when they might be needed/preferred.

**Comment by rhugman** [comment]
> @rhugman, is this one gtg? I know that it breaks with our tradition but do you reckon you could add some lines to the `prep_for_dsi()` docstring on the `ztz` and `energy` options and when they might be needed/preferred.

That might be helpful hey... :) roger wilco

**Comment by rhugman** [comment]
> @rhugman, is this one gtg? I know that it breaks with our tradition but do you reckon you could add some lines to the `prep_for_dsi()` docstring on the `ztz` and `energy` options and when they might be needed/preferred.

Should be good to go now.

**Comment by rhugman** [comment]
Should be good to go now. Tho it might not be a bad idea if someone double-checked my math...

**Comment by briochh** [comment]
I'm good, if you are good @rhugman!

**Pull request merged**
