### PR TITLE
Feat run_sp

### PR DESCRIPTION
**Pull request by p-ortega**
**This PR adds the `os_utils.run_sp()` function to run commands using `subprocess.Popen` as discussed in [532](https://github.com/pypest/pyemu/issues/532). The main function (`os_utils.run()`) will still use `os.system` by default, or call `run_sp()` if the `run_sp` option is set to `True`.**

Four unit tests were added to check stdout, log file output, and assert run success.

Additionally, `run_sp()` has been tested with some GMDSI tutorials, but I still need to test it on a real model.

Let me know what you think!

### CODE REVIEW

**Comment by p-ortega** [comment]
I need to fix my tests for macos and ubuntu .. I'll be back

**Comment by jtwhite79** [comment]
All good P!  Thanks for working on this!

**Comment by jtwhite79** [comment]
@p-ortega is the good to go?

**Comment by p-ortega** [comment]
@jtwhite79 I think is g2g now

**Pull request merged**
